# adapted from datasciencenotebook version a866877 fromn 1 Apr 18
# jplewis remove R stuff, pkg.add Knet,Images, update to julia0.6.3
# julia is installed into /opt/julia/
#
# docker build . -f Dockerfile-julia063-knet-nogpu-jupyter  -t julia063-knet-nogpu-jupyter 
# run with both working dir and data dir mounted
# docker run -p 8888:8888 -it --rm -e NB_UID=$(id -u) -e NB_GID=$(id -g) -e GRANT_SUDO=yes --user root  --mount type=bind,source="$(pwd)",target=/home/jovyan/work julia063-jupyter
# 
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
#FROM jupyter/scipy-notebook
FROM jupyter/minimal-notebook

LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"

# Set when building on Travis so that certain long-running build steps can
# be skipped to shorten build time.
ARG TEST_ONLY_BUILD

USER root

# R pre-requisites
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gfortran \
    gcc && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Julia dependencies
# install Julia packages in /opt/julia instead of $HOME
ENV JULIA_PKGDIR=/opt/julia
ENV JULIA_VERSION=0.6.3

RUN mkdir /opt/julia-${JULIA_VERSION} && \
    cd /tmp && \
    wget -q https://julialang-s3.julialang.org/bin/linux/x64/`echo ${JULIA_VERSION} | cut -d. -f 1,2`/julia-${JULIA_VERSION}-linux-x86_64.tar.gz && \
    echo "36212ed8e1c864599e9f149d884d504eee15b57b96bf918cb5b9ac35a5ab6283 *julia-${JULIA_VERSION}-linux-x86_64.tar.gz" | sha256sum -c - && \
    tar xzf julia-${JULIA_VERSION}-linux-x86_64.tar.gz -C /opt/julia-${JULIA_VERSION} --strip-components=1 && \
    rm /tmp/julia-${JULIA_VERSION}-linux-x86_64.tar.gz
RUN ln -fs /opt/julia-*/bin/julia /usr/local/bin/julia

# Show Julia where conda libraries are \
RUN mkdir /etc/julia && \
    echo "push!(Libdl.DL_LOAD_PATH, \"$CONDA_DIR/lib\")" >> /etc/julia/juliarc.jl && \
    # Create JULIA_PKGDIR \
    mkdir $JULIA_PKGDIR && \
    chown $NB_USER $JULIA_PKGDIR && \
    fix-permissions $JULIA_PKGDIR

USER $NB_UID

# Add Julia packages. Only add HDF5 if this is not a test-only build since
# it takes roughly half the entire build time of all of the images on Travis
# to add this one package and often causes Travis to timeout.
#
# Install IJulia as jovyan and then move the kernelspec out
# to the system share location. Avoids problems with runtime UID change not
# taking effect properly on the .local folder in the jovyan home dir.
RUN julia -e 'Pkg.init()' && \
    julia -e 'Pkg.update()' && \
    (test $TEST_ONLY_BUILD || julia -e 'Pkg.add("HDF5")') && \
    julia -e 'Pkg.add("Gadfly")' && \
    julia -e 'Pkg.add("IJulia")' && \
    julia -e 'Pkg.add("Knet")' && \
    julia -e 'Pkg.add("PyPlot")' && \
    # Precompile Julia packages \
    julia -e 'using IJulia' && \
    julia -e 'using Knet' && \
    julia -e 'Pkg.add("Images")' && \
    # move kernelspec out of home \
    mv $HOME/.local/share/jupyter/kernels/julia* $CONDA_DIR/share/jupyter/kernels/ && \
    chmod -R go+rx $CONDA_DIR/share/jupyter && \
    rm -rf $HOME/.local && \
    fix-permissions $JULIA_PKGDIR $CONDA_DIR/share/jupyter

# /opt/julia is owned by uid 1000. The USER command did not work?
#RUN sudo chown -R $NB_UID:$NB_GID /opt/julia
RUN chown -R $NB_UID:$NB_GID /opt/julia
#RUN chmod -R o+r /opt/julia/lib/v0.6	# otherwise get ERROR: LoadError: SystemError: opening file /opt/julia/lib/v0.6/IJulia.ji: Permission denied

# no, this is haunted
#RUN pip install jupyterthemes && jt -t chesterish
#RUN pip install jupyterthemes

# to get a command line run as "docker run ... start.sh bash"
